export default defineNuxtConfig({
  extends: ['../layers/docs', '../layers/theme'],
  compatibilityDate: '2025-01-01',
  // Project GitHub Pages site: https://jasenmichael.github.io/bros/
  app: {
    baseURL: '/bros/',
  },
  nitro: {
    baseURL: '/bros/',
    prerender: {
      routes: [
        '/',
        '/docs',
        '/docs/getting-started',
        '/docs/install',
        '/docs/environment',
        '/docs/configuration',
        '/docs/app',
        '/docs/chat',
        '/docs/models',
        '/docs/models-ollama',
        '/docs/models-custom',
        '/docs/status',
        '/docs/settings',
        '/docs/tunnel',
        '/docs/sidecars',
        '/docs/sidecars/ollama',
        '/docs/sidecars/opencode',
        '/docs/sidecars/openwebui',
        '/docs/sidecars/custom',
        '/docs/providers',
        '/docs/providers/gemini',
        '/docs/providers/groq',
        '/docs/providers/openrouter',
        '/docs/providers/mistral',
        '/docs/providers/cohere',
        '/docs/providers/openai',
        '/docs/providers/anthropic',
        '/docs/providers/deepseek',
        '/docs/providers/xai',
        '/docs/providers/together',
        '/docs/providers/fireworks',
        '/docs/providers/perplexity',
        '/docs/development',
        '/docs/website',
      ],
    },
  },
  vite: {
    base: '/bros/',
  },
})
